
spring.profiles.active: dev

#LOG
logging.config: classpath:log4j2.xml

# mybatis配置
mybatis:
  type-aliases-package: com.swellwu.po
  mapper-locations: classpath:mapper/*Mapper.xml

# 分页插件配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# druid配置
spring.datasource.druid:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: root
  maxActive: 20
  initialSize: 0
  maxWait: 60000
  minIdle: 1
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  maxOpenPreparedStatements: 20